#!/bin/sh
### BEGIN INIT INFO
# Provides: forever for family-budget-api
# Required-Start:
# Required-Stop:
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short Description: start and stop family-budget-api
# Description: FamilyBudgetAPI is a web service that allows data access to the budgeting data.
### END INIT INFO

case "$1" in
  start)
  exec forever --sourceDir=/var/www/family-budget-api start server.js
  ;;

  stop)
  exec forever stop --sourceDir=/var/www/family-budget-api server.js
  ;;
esac

exit 0
